### ISSUE TITLE
Mapbox navigation sdk updates; new Voice instructions powered by Amazon Polly

### ISSUE THREAD

**Issue by markscalf** [osmus/newsletter#14]
[Mapbox navigation sdk updates; new Voice instructions powered by Amazon Polly](https://www.mapbox.com/blog/navigation-ios-0.2/)

**Comment by iandees** [comment]
![image](https://cloud.githubusercontent.com/assets/261584/25415318/ee8016ea-2a04-11e7-8bad-e69d9ed67dac.png)


Mapbox [released a new version of their iOS navigation SDK](https://www.mapbox.com/blog/navigation-ios-0.2/). Notably, it integrates [Amazon's Polly service](https://aws.amazon.com/polly/) for voice navigation support.
