### ISSUE TITLE
Article:  A Different View of Mapping

### ISSUE THREAD

**Issue by markscalf** [osmus/newsletter#15]
[Article:  A Different View of Mapping](https://ssir.org/articles/entry/a_different_view_of_mapping?utm_content=bufferfec50&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer)

**Comment by iandees** [comment]
![image](https://cloud.githubusercontent.com/assets/261584/25414158/db6bb4da-29fd-11e7-88c9-959c34f515b9.png)


Noël Duan [wrote an article in the Spring 2017 issue of Stanford Social Innovation Review](https://ssir.org/articles/entry/a_different_view_of_mapping) giving an overview of the OpenStreetMap ecosystem, including mentions of Mapillary, Mapbox, and Visualizing Cities. A comparison is made between the crowdsourcing of OpenStreetMap and the private data collection of Google.
