### ISSUE TITLE
DG Imagery Announcement

### ISSUE THREAD

**Issue by markscalf** [osmus/newsletter#24]
[DG Imagery Announcement](http://blog.digitalglobe.com/news/digitalglobe-satellite-imagery-launch-for-openstreetmap/)

**Comment by iandees** [comment]
![image](https://cloud.githubusercontent.com/assets/261584/26033494/b961b16e-387b-11e7-9993-f178ded47d5d.png)

Digital Globe, a company that captures and distributes satellite imagery, [recently announced](http://blog.digitalglobe.com/news/digitalglobe-satellite-imagery-launch-for-openstreetmap/) that they made two new imagery layers available to OpenStreetMap for tracing and verification. The imagery is available in OpenStreetMap editors now!
