### ISSUE TITLE
9M buildings in 3D, 🙇 MS

### ISSUE THREAD

**Issue by jinalfoflia** [osmus/newsletter#40]
### Suggested Image

![s_84e7b247d5338be9520b8a8483b074e0fd480b2b4f57cb82133d69e69f44cee2_1497332968973_screen shot 2017-06-13 at 11 18 44 am](https://user-images.githubusercontent.com/4470913/27146469-088afe78-5157-11e7-933f-eeb79a14d2cb.png)

Baltimore ([live map](https://osmlab.github.io/ms-building-import/#13.86/39.2895/-76.6133/-1.2/60))

### Suggested Blurb

[Microsoft recently released 9.8 million building footprint data](http://wiki.openstreetmap.org/wiki/Microsoft_Building_Footprint_Data) covering 102 cities in 44 US states. Chetan Gowda created a [Mapbox map with 3D extrusion](https://www.openstreetmap.org/user/Chetan_Gowda/diary/41705) using this data and on inspection found the general quality of data being good and encouraged local communities to evaluate data for import.

**Comment by todrobbins** [comment]
But is it CityGML? 😜
