### ISSUE TITLE
Summer Mapathon in July

### ISSUE THREAD

**Issue by iandees** [osmus/newsletter#43]
### Suggested Image

![10140573715_2a6e0e021e_z](https://user-images.githubusercontent.com/261584/27493925-a6d441de-5819-11e7-9a93-4c0c69171191.jpg)
From [Flickr cc by-sa](https://www.flickr.com/photos/perspective/10140573715/in/photolist-gs66gR-eSBhDS-q5kMkk-e4T1P7-kk9jCJ-kk8SC6-fEzToE-edfvcW-ed9Pog-edfxU3-edfrYf-edfxfb-ae4fxi-gucTma-iDZ3qo-aQAjiP-qstAau-4nKdq7-4KFtiz-75Wvgx-6qYs53-bRSek2-gs7quQ-p8ykn1-7xKhTk-ed9Q24-ik44r9-e4Mphz-qCtPPV-gs4beb-gue25e-btjD48-bqiwQR-edfwAL-qsPHNd-edfutQ-5VXuRu-9HPUL2-cRGeHY-edfvUE-ed9NNe-edf9ts-67Qtgu-eSpSmP-2u1zjP-cuS6b3-po6Yg-ik4dgS-aRF8Xp-5VToJi)

### Suggested Blurb

The theme for [this Summer's OpenStreetMap US Mapathon is Bus Routes and Bus Stops](https://wiki.openstreetmap.org/wiki/Mapathon/US_Summer_Mapathon_2017). The Mapathon will occur throughout the United States over the weekend of July 15/16. The organizers are looking for more local mappers to participate. If this sounds interesting to you, check out [the wiki page](https://wiki.openstreetmap.org/wiki/Mapathon/US_Summer_Mapathon_2017) for details on how to join.

**Comment by awright** [comment]
@iandees can you put a message for people to sign up to host local events?

**Comment by iandees** [comment]
@awright can you suggest a sentence or two?

**Comment by awright** [comment]
OpenStreetMap US is hosting a Summer Mapathon this July. Consider signing up to host one in your local community. The suggested theme is transit and bus stops. Beat the Summer heat by traveling your favorite bus line and mapping for your favorite map. cc @iandees

**Comment by iandees** [comment]
Thanks @awright! I added a sentence to my description.
